blog/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from main import urls as blog_urls
from users import urls as users_urls
from main.views import post_list
from blog import settings

urlpatterns = [
    path('', post_list),
    path('admin/', admin.site.urls),
    path('blog/', include (blog_urls)),
    path('users/', include (users_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from .views import (index, post_list, about, contacts,
                    post_add, post_detail, post_update, post_delete, search)


app_name = 'main'
urlpatterns = [
    path('', index),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    
    path('posts/', post_list, name='post_list'),
    path('post_add/', post_add, name='post_add'),
    path('posts/<int:pk>/', post_detail, name='post_detail'),
    path('posts/<int:pk>/update/', post_update, name='post_update'),
    path('posts/<int:pk>/delete/', post_delete, name='post_delete'),
    path('posts/search/', search, name='search'),
]

users/urls.py
from django.urls import path
from .views import log_out, register, log_in, get_user_info


app_name = "users"
urlpatterns = [
    path("register/", register, name="register"),
    path("login/", log_in, name="login"),
    path("logout/", log_out, name="logout"),
    path("user/<int:pk>/", get_user_info, name="user_info"),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', editable=False)
    title = models.CharField(max_length=200, verbose_name='Заголовок', blank=False)
    text = models.TextField(blank=False, verbose_name='Текст')
    created_date = models.DateTimeField(default=timezone.now, editable=False)
    publish_date = models.DateTimeField(blank=True, null=True, editable=False)
    image = models.ImageField(upload_to='posts/', blank=True, null=True, verbose_name="Изображение поста")

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['created_date',]


    def publish(self):
        self.publish_date = timezone.now()
        self.save()


    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post


#class PostForm(forms.Form):
    #author = forms.CharField(max_length=50, label='Автор')
 #   title = forms.CharField(max_length=200, label='Заголовок')
  #  text = forms.CharField(widget=forms.Textarea, label="Текст поста")
   # image = forms.ImageField(required=False)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        #exclude = ['author']

      

main/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.http import HttpResponsePermanentRedirect
from django.contrib.auth.decorators import login_required

# Create your views here.

menu = [{"title" : "Посты", "url_name" : "main:post_list"}, 
        {"title" : "Добавить пост", "url_name" : "main:post_add"},
        {"title" : "О сайте", "url_name" : "main:about"},
        {"title" : "Контакты", "url_name" : "main:contacts"},
        ]
# Main page 
def index_root(request):
    return HttpResponsePermanentRedirect("/blog/posts")
# Main page of main app
def index(request):
    return HttpResponsePermanentRedirect("/blog/posts")

def about(request):
    title = "О сайте"
    context = {"title": title, "menu": menu}
    return render(request, 'main/about.html', context=context)

def contacts(request):
    title = "Контакты"
    context = {"title": title, "menu": menu}
    return render(request, 'main/contacts.html', context=context)

# отображения списка постов
def post_list(request, results=None):
    # получаем все обьекты таблицы(модели) Post
    if results is None:
        posts = Post.objects.all()
    else:
        posts = results
    # Заносим их в обьект контекста для передачи в шаблон
    context = {'posts': posts, 'menu': menu}
    return render(request, template_name= 'main/post_list.html', context=context)

@login_required
def post_add(request):
    title = "Create Post"
    if request.method == "GET":
        form = PostForm()
        context = {"title": title, "menu": menu, "form": form}
        return render(request, "main/post_add.html", context)
    
    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post = Post()
            post.author = request.user
            post.title = post_form.cleaned_data['title']
            post.text = post_form.cleaned_data['text']
            post.image = post_form.cleaned_data['image']
            post.publish()
            return post_list(request)
 
def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    title = "Информация о посте"
    context = {"post": post, "title": title, "menu":menu}
    return render(request, template_name="main/post_detail.html", context=context)


def post_update(request, pk):
    post = Post.objects.get(pk=pk)
    title = "Изменить пост"

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect("main:post_detail", pk=pk)
        
    form = PostForm(instance=post)
    return render(request, "main/post_update.html", context={"form": form, "title":title, "menu": menu})


def post_delete(request, pk):
    post = Post.objects.filter(pk=pk).first()

    if request.method == "POST":
        if "delete" in request.POST:
            post.delete()
            return redirect("main:post_list")
        if "cancel" in request.POST:
            return redirect("main:post_list")

    
    form = PostForm(instance=post)
    return render(request, "main/post_delete.html", {"form": form, "menu": menu, "post":post})

def search(request):
    query = request.GET.get('q')
    ft = Q(title__icontains=query)
    #results = Post.objects.filter(author__username=query)
    results = Post.objects.filter(ft)
    return post_list(request, results)

main/templates/main/about.html
{% extends "main/base.html" %}
      
{% block content %}
<h1>About site</h1>
{% endblock content %}

main/templates/main/base.html
{% load static %}
{% load thumbnail %}


<!DOCTYPE html>
<html>
    <head>
        <title>{{title}}</title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" type="text/css">

        <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" ></script>
        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" ></script>
        <script src="{% static 'js/popper.min.js' %}" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous" ></script>
        <style type="text/css">
            table {
             width: 800px;
            }
            th {
             background: #8c13e2; 
             color: #fffff0; register/
            }
            td, th {
             padding: 3px; 
            }
           </style>
    </head>

    <body TEXT="#000000" BGCOLOR="yellow" LINK="green">
      {% if user.is_authenticated %}
      nPuBeT, {{user.username}}
      <p><a href=" {% url 'users:logout' %}">Quit</a></p>
      {% endif %}

      {% if not user.is_authenticated %}
      
      <ul>
        <li><a href="{% url 'users:register' %}">Pегистрация</a></li>
        <li><a href="{% url 'users:login' %}">Войти</a></li>
      <ul>
      {% endif %}


        {% block head %}
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="#">
            <img src="{% static 'img/img_blog.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            My Blog 
          </a>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url menu.0.url_name %}">{{menu.0.title}}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url menu.1.url_name %}">{{menu.1.title}}<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url menu.2.url_name %}">{{menu.2.title}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url menu.3.url_name %}">{{menu.3.title}}</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Выпадающее меню
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
          </div>
        </nav>

        {% endblock head %}
        <img src="{% static 'img/img_blog.jpg' %}">
        <ul>
            {% for item in menu %}
                <h2><li><a href="{% url item.url_name %}">{{item.title}}</a></li></h2>
            {% endfor %}
        </ul>

    {% block content %}
    {% endblock  %} 
    </body>
</html>

main/templates/main/contacts.html
{% extends "main/base.html" %}
      
{% block content %}
<h1>Our contacts</h1>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}


{% block content %}
<h1>soderjanie</h1>
{% endblock content %}

main/templates/main/index_root.html
{% extends "main/base.html" %}
{% block content %}
<h1> This is main page of this site </h1>
{% endblock content %}

main/templates/main/post_add.html
{% extends "main/base.html" %}
 

{% block content %}

    <form action="{% url 'main:post_add'  %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="Submit"> Create post </button>
    </form>

{% endblock content %}

main/templates/main/post_delete.html
{% extends "main/base.html" %}


{% block content %}

<h1>Информация о посте</h1>
<p>Автор -  {{post.author}}</p>
<p>Заголовок - {{post.title}}</p>
<p>Текст поста - {{post.text}}</p>
<p>Дата создания - {{post.created_date}}</p>
<hr>

<h1>Удалить пост?</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    <button type="submit" name="delete">Удалить</button>
    <button type="submit" name="cancel">Отменить</button>
</form>

{% endblock content %}

main/templates/main/post_detail.html
{% extends "main/base.html" %}
{% load thumbnail %}

{% block content %}
        <h1>Информация о посте</h1>
        <p>Автор -  {{post.author}}</p>
        <p>Заголовок - {{post.title}}</p>
        <p>Текст поста - {{post.text}}</p>
        <p>Дата создания - {{post.created_date}}</p>
        
        {% thumbnail post.image "300x300" as im %}
        <img src="{{im.url}}" width="{{im.width}}" height="{{im.height}}">
        {% endthumbnail %}
        <hr>
        {% if request.user == post.author or request.user.id == 1 %}
            <a href="{% url "main:post_update" pk=post.id %}"> Редактировать </a>
        <hr>
            <a href="{% url "main:post_delete" pk=post.id %}"> Удалить </a>
        {% endif %}

{% endblock content %}

main/templates/main/post_list.html
{% extends "main/base.html" %}
{% block content %}
<form method="get" action="{% url "main:search" %}">
    <input type="text" name='q' value="">Поиск</input>
    <input type="submit" value="Search">

</form>
        <table id='posts' border=2>
            <th>ABTOP</th>
            <th>Заголовок</th>
            <th>Текст поста</th>
            <th>Дата создания</th>
        {% for post in posts %}
        <tr>
            <td align="center"><a href="{% url 'users:user_info' pk=post.author.id %}">{{post.author}}</a></td>
            <td align="center"><a href="{% url 'main:post_detail' pk=post.id %}">{{post.title}}<br><a></td>
            <td align="center">{{post.text}}<br></td>
            <td align="center">{{post.created_date}}<br></td>
        </tr>
        {% endfor %}
{% endblock content %}

main/templates/main/post_update.html
{% extends "main/base.html" %}

{% block content %}

<h1> Редактирование поста </h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">изменить пост</button>
</form>
{% endblock content %}